import { z } from 'zod';
import {
  createLocalDrafts,
  normalizeDraft,
  PLATFORM_ADAPTERS,
} from '../../shared/platformAdapters';
import {
  DEEPSEEK_MODEL,
  type AdaptationResult,
  type CanonicalContent,
  type PlatformDraft,
  type PlatformId,
} from '../../shared/types';

const DEFAULT_BASE_URL = 'https://api.deepseek.com';

const DraftSchema = z.object({
  platformId: z.enum(['wechat', 'zhihu', 'bilibili', 'xiaohongshu']),
  title: z.string(),
  summary: z.string(),
  body: z.string(),
  hashtags: z.array(z.string()).default([]),
  status: z.enum(['ready', 'needs-review']).default('ready'),
});

const DraftBundleSchema = z.object({
  drafts: z.array(DraftSchema),
});

const ChatCompletionSchema = z.object({
  choices: z.array(
    z.object({
      message: z.object({
        content: z.string(),
      }),
    }),
  ),
});

export interface GenerateAdaptationsOptions {
  content: CanonicalContent;
  apiKey?: string;
  baseUrl?: string;
  fetchImpl?: typeof fetch;
}

export async function generateAdaptations(
  options: GenerateAdaptationsOptions,
): Promise<AdaptationResult> {
  const localDrafts = createLocalDrafts(options.content);
  const apiKey = options.apiKey?.trim();

  if (!apiKey) {
    return {
      drafts: localDrafts,
      model: DEEPSEEK_MODEL,
      modelStatus: 'local-fallback',
      modelMessage: 'No DeepSeek API key configured. Local rule-based drafts were generated.',
    };
  }

  try {
    const response = await callDeepSeek(options, apiKey);
    const aiDrafts = parseDeepSeekDrafts(response);

    return {
      drafts: mergeDrafts(aiDrafts, localDrafts),
      model: DEEPSEEK_MODEL,
      modelStatus: 'ai',
      modelMessage: 'Generated by DeepSeek.',
    };
  } catch (error) {
    return {
      drafts: localDrafts,
      model: DEEPSEEK_MODEL,
      modelStatus: 'error-fallback',
      modelMessage: error instanceof Error ? error.message : 'DeepSeek request failed.',
    };
  }
}

async function callDeepSeek(options: GenerateAdaptationsOptions, apiKey: string): Promise<unknown> {
  const fetchImpl = options.fetchImpl ?? fetch;
  const baseUrl = (options.baseUrl ?? DEFAULT_BASE_URL).replace(/\/+$/, '');
  const response = await fetchImpl(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: DEEPSEEK_MODEL,
      temperature: 0.3,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content:
            'You are PostPilot, a Chinese creator publishing assistant. Return JSON only. Adapt the source content into platform-specific drafts for WeChat Official Account, Zhihu, Bilibili, and Xiaohongshu.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            source: options.content,
            requiredShape: {
              drafts: [
                {
                  platformId: 'wechat | zhihu | bilibili | xiaohongshu',
                  title: 'string',
                  summary: 'string',
                  body: 'string',
                  hashtags: ['string'],
                  status: 'ready',
                },
              ],
            },
            platformRules: PLATFORM_ADAPTERS.map((adapter) => ({
              id: adapter.id,
              displayName: adapter.displayName,
              tone: adapter.tone,
              limits: adapter.limits,
              exportFormat: adapter.exportFormat,
            })),
          }),
        },
      ],
    }),
  });

  if (!response.ok) {
    throw new Error(`DeepSeek request failed with HTTP ${response.status}.`);
  }

  return response.json();
}

function parseDeepSeekDrafts(payload: unknown): PlatformDraft[] {
  const completion = ChatCompletionSchema.parse(payload);
  const content = completion.choices[0]?.message.content;
  if (!content) {
    throw new Error('DeepSeek response did not include message content.');
  }

  const parsed = DraftBundleSchema.parse(JSON.parse(content));
  return parsed.drafts.map((draft) => normalizeDraft(draft));
}

function mergeDrafts(aiDrafts: PlatformDraft[], localDrafts: PlatformDraft[]): PlatformDraft[] {
  const aiByPlatform = new Map<PlatformId, PlatformDraft>(
    aiDrafts.map((draft) => [draft.platformId, draft]),
  );

  return PLATFORM_ADAPTERS.map((adapter) => aiByPlatform.get(adapter.id) ?? localDrafts.find(
    (draft) => draft.platformId === adapter.id,
  ))
    .filter((draft): draft is PlatformDraft => Boolean(draft))
    .map((draft) => normalizeDraft(draft));
}
